# PTB-friendly константы для ConversationHandler
CHOOSING_MAIN_SECTION = -1
CHOOSING_INITIAL_ACTION = 0
CHOOSING_BLOCK = 1
CHOOSING_MODE = 2
CHOOSING_TOPIC = 3
CHOOSING_EXAM_NUMBER = 4
ANSWERING = 5
CHOOSING_NEXT_ACTION = 6
REVIEWING_MISTAKES = 7

# Класс-обёртка для совместимости со старыми импортами QuizState
class QuizState:
    CHOOSING_MAIN_SECTION = CHOOSING_MAIN_SECTION
    CHOOSING_INITIAL_ACTION = CHOOSING_INITIAL_ACTION
    CHOOSING_BLOCK = CHOOSING_BLOCK
    CHOOSING_MODE = CHOOSING_MODE
    CHOOSING_TOPIC = CHOOSING_TOPIC
    CHOOSING_EXAM_NUMBER = CHOOSING_EXAM_NUMBER
    ANSWERING = ANSWERING
    CHOOSING_NEXT_ACTION = CHOOSING_NEXT_ACTION
    REVIEWING_MISTAKES = REVIEWING_MISTAKES
